import "./globals.css";
import { AuthProvider } from "@/providers/auth-provider";
export const metadata = {
  title: "E commerce Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
